In [ ]:
# first upload the file

In [10]:
from google.colab import files

uploaded = files.upload()

for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))

Saving IRISDataSet.prn to IRISDataSet.prn
User uploaded file "IRISDataSet.prn" with length 4700 bytes


Showing Data


In [12]:
import pandas as pd
import io
data=pd.read_csv(io.StringIO(uploaded['IRISDataSet.prn'].decode('utf-8')))
data.head()

5.1  3.5  1.4  0.2  Iris-setosa
0  4.9  3.0  1.4  0.2  Iris-setosa
1  4.7  3.2  1.3  0.2  Iris-setosa
2  4.6  3.1  1.5  0.2  Iris-setosa
3  5.0  3.6  1.4  0.2  Iris-setosa
4  5.4  3.9  1.7  0.4  Iris-setosa

Adding more data

In [15]:
import keras
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam
import matplotlib.pyplot as plt
import graphviz
from IPython.display import SVG
from keras.utils.vis_utils import model_to_dot
from keras.utils import plot_model
import seaborn as sns
import pandas as pd
import numpy as np




In [21]:
dataset=pd.read_csv('IRISDataSet.prn')
dataset

5.1  3.5  1.4  0.2     Iris-setosa
0    4.9  3.0  1.4  0.2     Iris-setosa
1    4.7  3.2  1.3  0.2     Iris-setosa
2    4.6  3.1  1.5  0.2     Iris-setosa
3    5.0  3.6  1.4  0.2     Iris-setosa
4    5.4  3.9  1.7  0.4     Iris-setosa
..   ...  ...  ...  ...             ...
144  6.7  3.0  5.2  2.3  Iris-virginica
145  6.3  2.5  5.0  1.9  Iris-virginica
146  6.5  3.0  5.2  2.0  Iris-virginica
147  6.2  3.4  5.4  2.3  Iris-virginica
148  5.9  3.0  5.1  1.8  Iris-virginica

[149 rows x 5 columns]

In [24]:
X=dataset.iloc[:,0:4].values
y=dataset.iloc[:,4].values

Encoding categorical data

In [28]:
from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()
y1=encoder.fit_transform(y)
Y=pd.get_dummies(y1).values


Splitting the dataset into the Training and Test set

In [29]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,Y,test_size=0.2,random_state=0)

Add the model and first hidden layer

In [30]:
model=Sequential()

model.add(Dense(4,input_shape=(4,),activation='relu')) # input layer

model.add(Dense(3,activation='softmax')) # output layer



In [31]:
model.compile(optimizer="Adam",loss='categorical_crossentropy',metrics=['accuracy']) # compiler

Training state

In [35]:
model.fit(X_train,y_train,batch_size=10,epochs=200)

Epoch 1/200
12/12 [==============================] - 0s 1ms/step - loss: 0.5087 - accuracy: 0.6639
Epoch 2/200
12/12 [==============================] - 0s 1ms/step - loss: 0.5086 - accuracy: 0.6639
Epoch 3/200
12/12 [==============================] - 0s 1ms/step - loss: 0.5083 - accuracy: 0.6639
Epoch 4/200
12/12 [==============================] - 0s 1ms/step - loss: 0.5081 - accuracy: 0.6639
Epoch 5/200
12/12 [==============================] - 0s 1ms/step - loss: 0.5078 - accuracy: 0.6639
Epoch 6/200
12/12 [==============================] - 0s 1ms/step - loss: 0.5076 - accuracy: 0.6639
Epoch 7/200
12/12 [==============================] - 0s 1ms/step - loss: 0.5074 - accuracy: 0.6639
Epoch 8/200
12/12 [==============================] - 0s 1ms/step - loss: 0.5072 - accuracy: 0.6639
Epoch 9/200
12/12 [==============================] - 0s 1ms/step - loss: 0.5071 - accuracy: 0.6639
Epoch 10/200
12/12 [==============================] - 0s 1ms/step - loss: 0.5068 - accuracy: 0.6639
Epoch 11/

Predicting the Test set results

In [37]:
y_pred=model.predict(X_test)
y_test_class=np.argmax(y_test,axis=1)
y_pred_class=np.argmax(y_pred,axis=1)

Making the Confusion Matrix

In [38]:
from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(y_test_class,y_pred_class))
print(confusion_matrix(y_test_class,y_pred_class))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       0.83      1.00      0.91        10
           2       1.00      0.75      0.86         8

    accuracy                           0.93        30
   macro avg       0.94      0.92      0.92        30
weighted avg       0.94      0.93      0.93        30

[[12  0  0]
 [ 0 10  0]
 [ 0  2  6]]
